name: release

on:
  push:
    branches: ['master', 'develop']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Running linting and tests
        run: yarn fix
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Building extension
        run: yarn build
      - name: Set CHROME_TARGET environment variable
        # if the branch is main, set CHROME_TARGET to default, which will publish to the Chrome Web Store
        # otherwise, set CHROME_TARGET to local, which will not publish to the Chrome Web Store at all
        run: |
         if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then 
           echo "CHROME_TARGET=default" >> $GITHUB_ENV
         else
           echo "CHROME_TARGET=local" >> $GITHUB_ENV
         fi
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: npx semantic-release
